// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sentence.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sentence_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_sentence_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_sentence_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_sentence_2eproto {
  static const ::uint32_t offsets[];
};
namespace chrome_lang_id {
class Sentence;
struct SentenceDefaultTypeInternal;
extern SentenceDefaultTypeInternal _Sentence_default_instance_;
class Token;
struct TokenDefaultTypeInternal;
extern TokenDefaultTypeInternal _Token_default_instance_;
}  // namespace chrome_lang_id
namespace google {
namespace protobuf {
template <>
::chrome_lang_id::Sentence* Arena::CreateMaybeMessage<::chrome_lang_id::Sentence>(Arena*);
template <>
::chrome_lang_id::Token* Arena::CreateMaybeMessage<::chrome_lang_id::Token>(Arena*);
}  // namespace protobuf
}  // namespace google

namespace chrome_lang_id {
enum Token_BreakLevel : int {
  Token_BreakLevel_NO_BREAK = 0,
  Token_BreakLevel_SPACE_BREAK = 1,
  Token_BreakLevel_LINE_BREAK = 2,
  Token_BreakLevel_SENTENCE_BREAK = 3,
};

bool Token_BreakLevel_IsValid(int value);
constexpr Token_BreakLevel Token_BreakLevel_BreakLevel_MIN = static_cast<Token_BreakLevel>(0);
constexpr Token_BreakLevel Token_BreakLevel_BreakLevel_MAX = static_cast<Token_BreakLevel>(3);
constexpr int Token_BreakLevel_BreakLevel_ARRAYSIZE = 3 + 1;
const std::string& Token_BreakLevel_Name(Token_BreakLevel value);
template <typename T>
const std::string& Token_BreakLevel_Name(T value) {
  static_assert(std::is_same<T, Token_BreakLevel>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to BreakLevel_Name().");
  return Token_BreakLevel_Name(static_cast<Token_BreakLevel>(value));
}
const std::string& Token_BreakLevel_Name(Token_BreakLevel value);
bool Token_BreakLevel_Parse(absl::string_view name, Token_BreakLevel* value);

// ===================================================================


// -------------------------------------------------------------------

class Sentence final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:chrome_lang_id.Sentence) */ {
 public:
  inline Sentence() : Sentence(nullptr) {}
  ~Sentence() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Sentence(::google::protobuf::internal::ConstantInitialized);

  Sentence(const Sentence& from);
  Sentence(Sentence&& from) noexcept
    : Sentence() {
    *this = ::std::move(from);
  }

  inline Sentence& operator=(const Sentence& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sentence& operator=(Sentence&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const Sentence& default_instance() {
    return *internal_default_instance();
  }
  static inline const Sentence* internal_default_instance() {
    return reinterpret_cast<const Sentence*>(
               &_Sentence_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Sentence& a, Sentence& b) {
    a.Swap(&b);
  }
  inline void Swap(Sentence* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sentence* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Sentence* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Sentence>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)  final;
  void CopyFrom(const Sentence& from);
  void MergeFrom(const Sentence& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Sentence* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "chrome_lang_id.Sentence";
  }
  protected:
  explicit Sentence(::google::protobuf::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokenFieldNumber = 3,
    kIdFieldNumber = 1,
    kTextFieldNumber = 2,
  };
  // repeated .chrome_lang_id.Token token = 3;
  int token_size() const;
  private:
  int _internal_token_size() const;

  public:
  void clear_token() ;
  ::chrome_lang_id::Token* mutable_token(int index);
  ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::Token >*
      mutable_token();
  private:
  const ::google::protobuf::RepeatedPtrField<::chrome_lang_id::Token>& _internal_token() const;
  ::google::protobuf::RepeatedPtrField<::chrome_lang_id::Token>* _internal_mutable_token();
  public:
  const ::chrome_lang_id::Token& token(int index) const;
  ::chrome_lang_id::Token* add_token();
  const ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::Token >&
      token() const;
  // optional string id = 1;
  bool has_id() const;
  void clear_id() ;
  const std::string& id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* ptr);

  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(
      const std::string& value);
  std::string* _internal_mutable_id();

  public:
  // optional string text = 2;
  bool has_text() const;
  void clear_text() ;
  const std::string& text() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_text(Arg_&& arg, Args_... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* ptr);

  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(
      const std::string& value);
  std::string* _internal_mutable_text();

  public:
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline bool HasExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _impl_._extensions_.Has(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void ClearExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    _impl_._extensions_.ClearExtension(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline int ExtensionSize(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _impl_._extensions_.ExtensionSize(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, id.default_value());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType MutableExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    return _proto_TypeTraits::Mutable(id.number(), _field_type, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::ConstType value) {
    _proto_TypeTraits::Set(id.number(), _field_type, value, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetAllocatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::SetAllocated(id.number(), _field_type, value,
                                    &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void UnsafeArenaSetAllocatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::UnsafeArenaSetAllocated(id.number(), _field_type,
                                               value, &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  PROTOBUF_NODISCARD inline
      typename _proto_TypeTraits::Singular::MutableType
      ReleaseExtension(
          const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                           _field_type, _is_packed>& id) {
    return _proto_TypeTraits::Release(id.number(), _field_type, &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType
  UnsafeArenaReleaseExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    return _proto_TypeTraits::UnsafeArenaRelease(id.number(), _field_type,
                                                 &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) const {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, index);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType MutableExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) {
    return _proto_TypeTraits::Mutable(id.number(), index, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index, typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Set(id.number(), index, value, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType AddExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    typename _proto_TypeTraits::Repeated::MutableType to_add =
        _proto_TypeTraits::Add(id.number(), _field_type, &_impl_._extensions_);
    return to_add;
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void AddExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Add(id.number(), _field_type, _is_packed, value,
                           &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline const typename _proto_TypeTraits::Repeated::RepeatedFieldType&
  GetRepeatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _proto_TypeTraits::GetRepeated(id.number(), _impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::RepeatedFieldType*
  MutableRepeatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Sentence, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    return _proto_TypeTraits::MutableRepeated(id.number(), _field_type,
                                              _is_packed, &_impl_._extensions_);
  }
  // @@protoc_insertion_point(class_scope:chrome_lang_id.Sentence)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3, 1, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::ExtensionSet _extensions_;

    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::Token > token_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr text_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sentence_2eproto;
};// -------------------------------------------------------------------

class Token final :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:chrome_lang_id.Token) */ {
 public:
  inline Token() : Token(nullptr) {}
  ~Token() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Token(::google::protobuf::internal::ConstantInitialized);

  Token(const Token& from);
  Token(Token&& from) noexcept
    : Token() {
    *this = ::std::move(from);
  }

  inline Token& operator=(const Token& from) {
    CopyFrom(from);
    return *this;
  }
  inline Token& operator=(Token&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const Token& default_instance() {
    return *internal_default_instance();
  }
  static inline const Token* internal_default_instance() {
    return reinterpret_cast<const Token*>(
               &_Token_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Token& a, Token& b) {
    a.Swap(&b);
  }
  inline void Swap(Token* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Token* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Token* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Token>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)  final;
  void CopyFrom(const Token& from);
  void MergeFrom(const Token& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Token* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "chrome_lang_id.Token";
  }
  protected:
  explicit Token(::google::protobuf::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  using BreakLevel = Token_BreakLevel;
  static constexpr BreakLevel NO_BREAK = Token_BreakLevel_NO_BREAK;
  static constexpr BreakLevel SPACE_BREAK = Token_BreakLevel_SPACE_BREAK;
  static constexpr BreakLevel LINE_BREAK = Token_BreakLevel_LINE_BREAK;
  static constexpr BreakLevel SENTENCE_BREAK = Token_BreakLevel_SENTENCE_BREAK;
  static inline bool BreakLevel_IsValid(int value) {
    return Token_BreakLevel_IsValid(value);
  }
  static constexpr BreakLevel BreakLevel_MIN = Token_BreakLevel_BreakLevel_MIN;
  static constexpr BreakLevel BreakLevel_MAX = Token_BreakLevel_BreakLevel_MAX;
  static constexpr int BreakLevel_ARRAYSIZE = Token_BreakLevel_BreakLevel_ARRAYSIZE;
  template <typename T>
  static inline const std::string& BreakLevel_Name(T value) {
    return Token_BreakLevel_Name(value);
  }
  static inline bool BreakLevel_Parse(absl::string_view name, BreakLevel* value) {
    return Token_BreakLevel_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kWordFieldNumber = 1,
    kTagFieldNumber = 5,
    kCategoryFieldNumber = 6,
    kLabelFieldNumber = 7,
    kStartFieldNumber = 2,
    kEndFieldNumber = 3,
    kHeadFieldNumber = 4,
    kBreakLevelFieldNumber = 8,
  };
  // required string word = 1;
  bool has_word() const;
  void clear_word() ;
  const std::string& word() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_word(Arg_&& arg, Args_... args);
  std::string* mutable_word();
  PROTOBUF_NODISCARD std::string* release_word();
  void set_allocated_word(std::string* ptr);

  private:
  const std::string& _internal_word() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_word(
      const std::string& value);
  std::string* _internal_mutable_word();

  public:
  // optional string tag = 5;
  bool has_tag() const;
  void clear_tag() ;
  const std::string& tag() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_tag(Arg_&& arg, Args_... args);
  std::string* mutable_tag();
  PROTOBUF_NODISCARD std::string* release_tag();
  void set_allocated_tag(std::string* ptr);

  private:
  const std::string& _internal_tag() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tag(
      const std::string& value);
  std::string* _internal_mutable_tag();

  public:
  // optional string category = 6;
  bool has_category() const;
  void clear_category() ;
  const std::string& category() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_category(Arg_&& arg, Args_... args);
  std::string* mutable_category();
  PROTOBUF_NODISCARD std::string* release_category();
  void set_allocated_category(std::string* ptr);

  private:
  const std::string& _internal_category() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_category(
      const std::string& value);
  std::string* _internal_mutable_category();

  public:
  // optional string label = 7;
  bool has_label() const;
  void clear_label() ;
  const std::string& label() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_label(Arg_&& arg, Args_... args);
  std::string* mutable_label();
  PROTOBUF_NODISCARD std::string* release_label();
  void set_allocated_label(std::string* ptr);

  private:
  const std::string& _internal_label() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_label(
      const std::string& value);
  std::string* _internal_mutable_label();

  public:
  // required int32 start = 2;
  bool has_start() const;
  void clear_start() ;
  ::int32_t start() const;
  void set_start(::int32_t value);

  private:
  ::int32_t _internal_start() const;
  void _internal_set_start(::int32_t value);

  public:
  // required int32 end = 3;
  bool has_end() const;
  void clear_end() ;
  ::int32_t end() const;
  void set_end(::int32_t value);

  private:
  ::int32_t _internal_end() const;
  void _internal_set_end(::int32_t value);

  public:
  // optional int32 head = 4 [default = -1];
  bool has_head() const;
  void clear_head() ;
  ::int32_t head() const;
  void set_head(::int32_t value);

  private:
  ::int32_t _internal_head() const;
  void _internal_set_head(::int32_t value);

  public:
  // optional .chrome_lang_id.Token.BreakLevel break_level = 8 [default = SPACE_BREAK];
  bool has_break_level() const;
  void clear_break_level() ;
  ::chrome_lang_id::Token_BreakLevel break_level() const;
  void set_break_level(::chrome_lang_id::Token_BreakLevel value);

  private:
  ::chrome_lang_id::Token_BreakLevel _internal_break_level() const;
  void _internal_set_break_level(::chrome_lang_id::Token_BreakLevel value);

  public:
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline bool HasExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _impl_._extensions_.Has(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void ClearExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    _impl_._extensions_.ClearExtension(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline int ExtensionSize(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _impl_._extensions_.ExtensionSize(id.number());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, id.default_value());
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType MutableExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    return _proto_TypeTraits::Mutable(id.number(), _field_type, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::ConstType value) {
    _proto_TypeTraits::Set(id.number(), _field_type, value, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetAllocatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::SetAllocated(id.number(), _field_type, value,
                                    &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void UnsafeArenaSetAllocatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Singular::MutableType value) {
    _proto_TypeTraits::UnsafeArenaSetAllocated(id.number(), _field_type,
                                               value, &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  PROTOBUF_NODISCARD inline
      typename _proto_TypeTraits::Singular::MutableType
      ReleaseExtension(
          const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                           _field_type, _is_packed>& id) {
    return _proto_TypeTraits::Release(id.number(), _field_type, &_impl_._extensions_);
  }
  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Singular::MutableType
  UnsafeArenaReleaseExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    return _proto_TypeTraits::UnsafeArenaRelease(id.number(), _field_type,
                                                 &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::ConstType GetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) const {
    return _proto_TypeTraits::Get(id.number(), _impl_._extensions_, index);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType MutableExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index) {
    return _proto_TypeTraits::Mutable(id.number(), index, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void SetExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      int index, typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Set(id.number(), index, value, &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::MutableType AddExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    typename _proto_TypeTraits::Repeated::MutableType to_add =
        _proto_TypeTraits::Add(id.number(), _field_type, &_impl_._extensions_);
    return to_add;
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline void AddExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id,
      typename _proto_TypeTraits::Repeated::ConstType value) {
    _proto_TypeTraits::Add(id.number(), _field_type, _is_packed, value,
                           &_impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline const typename _proto_TypeTraits::Repeated::RepeatedFieldType&
  GetRepeatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) const {
    return _proto_TypeTraits::GetRepeated(id.number(), _impl_._extensions_);
  }

  template <typename _proto_TypeTraits, ::google::protobuf::internal::FieldType _field_type,
            bool _is_packed>
  inline typename _proto_TypeTraits::Repeated::RepeatedFieldType*
  MutableRepeatedExtension(
      const ::google::protobuf::internal::ExtensionIdentifier<Token, _proto_TypeTraits,
                                       _field_type, _is_packed>& id) {
    return _proto_TypeTraits::MutableRepeated(id.number(), _field_type,
                                              _is_packed, &_impl_._extensions_);
  }
  // @@protoc_insertion_point(class_scope:chrome_lang_id.Token)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8, 1, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::ExtensionSet _extensions_;

    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr word_;
    ::google::protobuf::internal::ArenaStringPtr tag_;
    ::google::protobuf::internal::ArenaStringPtr category_;
    ::google::protobuf::internal::ArenaStringPtr label_;
    ::int32_t start_;
    ::int32_t end_;
    ::int32_t head_;
    int break_level_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sentence_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Sentence

// optional string id = 1;
inline bool Sentence::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Sentence::clear_id() {
  _impl_.id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Sentence::id() const {
  // @@protoc_insertion_point(field_get:chrome_lang_id.Sentence.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Sentence::set_id(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrome_lang_id.Sentence.id)
}
inline std::string* Sentence::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:chrome_lang_id.Sentence.id)
  return _s;
}
inline const std::string& Sentence::_internal_id() const {
  return _impl_.id_.Get();
}
inline void Sentence::_internal_set_id(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* Sentence::_internal_mutable_id() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.id_.Mutable( GetArenaForAllocation());
}
inline std::string* Sentence::release_id() {
  // @@protoc_insertion_point(field_release:chrome_lang_id.Sentence.id)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.id_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Sentence::set_allocated_id(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.id_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.id_.IsDefault()) {
          _impl_.id_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrome_lang_id.Sentence.id)
}

// optional string text = 2;
inline bool Sentence::has_text() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Sentence::clear_text() {
  _impl_.text_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Sentence::text() const {
  // @@protoc_insertion_point(field_get:chrome_lang_id.Sentence.text)
  return _internal_text();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Sentence::set_text(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.text_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrome_lang_id.Sentence.text)
}
inline std::string* Sentence::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:chrome_lang_id.Sentence.text)
  return _s;
}
inline const std::string& Sentence::_internal_text() const {
  return _impl_.text_.Get();
}
inline void Sentence::_internal_set_text(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* Sentence::_internal_mutable_text() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.text_.Mutable( GetArenaForAllocation());
}
inline std::string* Sentence::release_text() {
  // @@protoc_insertion_point(field_release:chrome_lang_id.Sentence.text)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.text_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.text_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Sentence::set_allocated_text(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.text_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.text_.IsDefault()) {
          _impl_.text_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrome_lang_id.Sentence.text)
}

// repeated .chrome_lang_id.Token token = 3;
inline int Sentence::_internal_token_size() const {
  return _internal_token().size();
}
inline int Sentence::token_size() const {
  return _internal_token_size();
}
inline void Sentence::clear_token() {
  _internal_mutable_token()->Clear();
}
inline ::chrome_lang_id::Token* Sentence::mutable_token(int index) {
  // @@protoc_insertion_point(field_mutable:chrome_lang_id.Sentence.token)
  return _internal_mutable_token()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::Token >*
Sentence::mutable_token() {
  // @@protoc_insertion_point(field_mutable_list:chrome_lang_id.Sentence.token)
  PROTOBUF_TSAN_WRITE(&_impl_);
  return _internal_mutable_token();
}
inline const ::chrome_lang_id::Token& Sentence::token(int index) const {
  // @@protoc_insertion_point(field_get:chrome_lang_id.Sentence.token)
    return _internal_token().Get(index);
}
inline ::chrome_lang_id::Token* Sentence::add_token() {
  PROTOBUF_TSAN_WRITE(&_impl_);
  ::chrome_lang_id::Token* _add = _internal_mutable_token()->Add();
  // @@protoc_insertion_point(field_add:chrome_lang_id.Sentence.token)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::Token >&
Sentence::token() const {
  // @@protoc_insertion_point(field_list:chrome_lang_id.Sentence.token)
  return _internal_token();
}
inline const ::google::protobuf::RepeatedPtrField<::chrome_lang_id::Token>&
Sentence::_internal_token() const {
  PROTOBUF_TSAN_READ(&_impl_);
  return _impl_.token_;
}
inline ::google::protobuf::RepeatedPtrField<::chrome_lang_id::Token>*
Sentence::_internal_mutable_token() {
  PROTOBUF_TSAN_READ(&_impl_);
  return &_impl_.token_;
}

// -------------------------------------------------------------------

// Token

// required string word = 1;
inline bool Token::has_word() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Token::clear_word() {
  _impl_.word_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Token::word() const {
  // @@protoc_insertion_point(field_get:chrome_lang_id.Token.word)
  return _internal_word();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Token::set_word(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.word_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrome_lang_id.Token.word)
}
inline std::string* Token::mutable_word() {
  std::string* _s = _internal_mutable_word();
  // @@protoc_insertion_point(field_mutable:chrome_lang_id.Token.word)
  return _s;
}
inline const std::string& Token::_internal_word() const {
  return _impl_.word_.Get();
}
inline void Token::_internal_set_word(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.word_.Set(value, GetArenaForAllocation());
}
inline std::string* Token::_internal_mutable_word() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.word_.Mutable( GetArenaForAllocation());
}
inline std::string* Token::release_word() {
  // @@protoc_insertion_point(field_release:chrome_lang_id.Token.word)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.word_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.word_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Token::set_allocated_word(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.word_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.word_.IsDefault()) {
          _impl_.word_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrome_lang_id.Token.word)
}

// required int32 start = 2;
inline bool Token::has_start() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void Token::clear_start() {
  _impl_.start_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t Token::start() const {
  // @@protoc_insertion_point(field_get:chrome_lang_id.Token.start)
  return _internal_start();
}
inline void Token::set_start(::int32_t value) {
  _internal_set_start(value);
  // @@protoc_insertion_point(field_set:chrome_lang_id.Token.start)
}
inline ::int32_t Token::_internal_start() const {
  return _impl_.start_;
}
inline void Token::_internal_set_start(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.start_ = value;
}

// required int32 end = 3;
inline bool Token::has_end() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void Token::clear_end() {
  _impl_.end_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t Token::end() const {
  // @@protoc_insertion_point(field_get:chrome_lang_id.Token.end)
  return _internal_end();
}
inline void Token::set_end(::int32_t value) {
  _internal_set_end(value);
  // @@protoc_insertion_point(field_set:chrome_lang_id.Token.end)
}
inline ::int32_t Token::_internal_end() const {
  return _impl_.end_;
}
inline void Token::_internal_set_end(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.end_ = value;
}

// optional int32 head = 4 [default = -1];
inline bool Token::has_head() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void Token::clear_head() {
  _impl_.head_ = -1;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::int32_t Token::head() const {
  // @@protoc_insertion_point(field_get:chrome_lang_id.Token.head)
  return _internal_head();
}
inline void Token::set_head(::int32_t value) {
  _internal_set_head(value);
  // @@protoc_insertion_point(field_set:chrome_lang_id.Token.head)
}
inline ::int32_t Token::_internal_head() const {
  return _impl_.head_;
}
inline void Token::_internal_set_head(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.head_ = value;
}

// optional string tag = 5;
inline bool Token::has_tag() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Token::clear_tag() {
  _impl_.tag_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Token::tag() const {
  // @@protoc_insertion_point(field_get:chrome_lang_id.Token.tag)
  return _internal_tag();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Token::set_tag(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.tag_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrome_lang_id.Token.tag)
}
inline std::string* Token::mutable_tag() {
  std::string* _s = _internal_mutable_tag();
  // @@protoc_insertion_point(field_mutable:chrome_lang_id.Token.tag)
  return _s;
}
inline const std::string& Token::_internal_tag() const {
  return _impl_.tag_.Get();
}
inline void Token::_internal_set_tag(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.tag_.Set(value, GetArenaForAllocation());
}
inline std::string* Token::_internal_mutable_tag() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.tag_.Mutable( GetArenaForAllocation());
}
inline std::string* Token::release_tag() {
  // @@protoc_insertion_point(field_release:chrome_lang_id.Token.tag)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.tag_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.tag_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Token::set_allocated_tag(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.tag_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.tag_.IsDefault()) {
          _impl_.tag_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrome_lang_id.Token.tag)
}

// optional string category = 6;
inline bool Token::has_category() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Token::clear_category() {
  _impl_.category_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Token::category() const {
  // @@protoc_insertion_point(field_get:chrome_lang_id.Token.category)
  return _internal_category();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Token::set_category(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.category_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrome_lang_id.Token.category)
}
inline std::string* Token::mutable_category() {
  std::string* _s = _internal_mutable_category();
  // @@protoc_insertion_point(field_mutable:chrome_lang_id.Token.category)
  return _s;
}
inline const std::string& Token::_internal_category() const {
  return _impl_.category_.Get();
}
inline void Token::_internal_set_category(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.category_.Set(value, GetArenaForAllocation());
}
inline std::string* Token::_internal_mutable_category() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.category_.Mutable( GetArenaForAllocation());
}
inline std::string* Token::release_category() {
  // @@protoc_insertion_point(field_release:chrome_lang_id.Token.category)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.category_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.category_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Token::set_allocated_category(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.category_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.category_.IsDefault()) {
          _impl_.category_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrome_lang_id.Token.category)
}

// optional string label = 7;
inline bool Token::has_label() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Token::clear_label() {
  _impl_.label_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& Token::label() const {
  // @@protoc_insertion_point(field_get:chrome_lang_id.Token.label)
  return _internal_label();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Token::set_label(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.label_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chrome_lang_id.Token.label)
}
inline std::string* Token::mutable_label() {
  std::string* _s = _internal_mutable_label();
  // @@protoc_insertion_point(field_mutable:chrome_lang_id.Token.label)
  return _s;
}
inline const std::string& Token::_internal_label() const {
  return _impl_.label_.Get();
}
inline void Token::_internal_set_label(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.label_.Set(value, GetArenaForAllocation());
}
inline std::string* Token::_internal_mutable_label() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.label_.Mutable( GetArenaForAllocation());
}
inline std::string* Token::release_label() {
  // @@protoc_insertion_point(field_release:chrome_lang_id.Token.label)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.label_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.label_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Token::set_allocated_label(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.label_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.label_.IsDefault()) {
          _impl_.label_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chrome_lang_id.Token.label)
}

// optional .chrome_lang_id.Token.BreakLevel break_level = 8 [default = SPACE_BREAK];
inline bool Token::has_break_level() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void Token::clear_break_level() {
  _impl_.break_level_ = 1;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::chrome_lang_id::Token_BreakLevel Token::break_level() const {
  // @@protoc_insertion_point(field_get:chrome_lang_id.Token.break_level)
  return _internal_break_level();
}
inline void Token::set_break_level(::chrome_lang_id::Token_BreakLevel value) {
   _internal_set_break_level(value);
  // @@protoc_insertion_point(field_set:chrome_lang_id.Token.break_level)
}
inline ::chrome_lang_id::Token_BreakLevel Token::_internal_break_level() const {
  return static_cast<::chrome_lang_id::Token_BreakLevel>(_impl_.break_level_);
}
inline void Token::_internal_set_break_level(::chrome_lang_id::Token_BreakLevel value) {
  assert(::chrome_lang_id::Token_BreakLevel_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.break_level_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace chrome_lang_id


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::chrome_lang_id::Token_BreakLevel> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_sentence_2eproto_2epb_2eh
